### ISSUE TITLE
Check out and add collaborative editor

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#77]
@prologic has created a realtime collaborative editor with circuits - we'll need to integrate it and make it available as default editor

**Comment by prologic** [comment]
Haha :) I did mention *prototype* right?

If you're serious about it; we'll have to fix a few bugs to do with synchronization of events from multiple clients; at the moment it's using a Lamport clock but there are a few issues. It also only uses a basic textarea with a jQuery plugin on the frontend right now so that side of it will have to be expanded too to be a bit more of a decent editor :)

Happy to put i up as a demo somewhere for you to play with?

**Comment by ri0t** [comment]
I am building something which resembles easysync from etherpad - just for generic objects.
